<a href="https://colab.research.google.com/github/SobolMaria/goit-ds-hw-04/blob/main/task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [6]:
arr = np.array([0, 1, 2, 3])

arr_22 = arr.reshape(2,2)
print(arr_22)

[[0 1]
 [2 3]]


3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [10]:
arr1 = np.array([[0, 1], [2, 3]])
arr2 = np.array([[4, 5], [6, 7]])

arr12 = np.concatenate((arr1,arr2), axis=0)
print(arr12)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])



In [12]:
a = np.array([1,2,3])

a_output = ([a[0], a[0], a[0], a[1], a[1], a[1], a[2], a[2], a[2], a[0], a[1], a[2], a[0], a[1], a[2], a[0], a[1], a[2]])
print(a_output)

[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


5. Отримайте спільні елементи між a і b

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
print(c)


[2 4]


6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

In [25]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)
indices_max = np.argsort(a)[-5:][::-1]
print(indices_max)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


7. Вилучіть усі значення NaN із одновимірного масиву

In [23]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a_new = a[~np.isnan(a)]

print(a_new)

[1. 2. 3. 5. 6. 7.]


8. Обчисліть евклідову відстань між двома масивами a і b.

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

evkl_dist = np.linalg.norm(a-b)
print(evkl_dist)

6.708203932499369


9. Знайдіть індекс 5-го повторення числа 1 у масиві x

In [32]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

indices = np.where(x == 1)[0]
place = indices[4]
print(place)

8


10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

In [37]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)

result = np.zeros_like(a, dtype=bool)
seen = set()

for i, val in enumerate(a):
    if val in seen:
        result[i] = True
    else:
        seen.add(val)

print(result)


[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
