<a href="https://colab.research.google.com/github/SobolMaria/goit-ds-hw-04/blob/main/task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [9]:
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
b = np.zeros((3, 3), dtype="int")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
c = np.random.randint( 11, size=(5,5))
print(c)

[[ 7 10  6  4  6]
 [ 3  4  7  7  7]
 [ 3  4  2  8  4]
 [10  9  9  7  0]
 [ 2  7  9  5  0]]


In [17]:
d = np.random.random((4,4))
print(d)

[[0.23107808 0.17752675 0.65396085 0.61093147]
 [0.78990773 0.88035784 0.36941836 0.17429784]
 [0.476626   0.45326279 0.64876399 0.83469081]
 [0.43954909 0.47516639 0.27863298 0.23150067]]


In [26]:
a = np.random.randint(1,11, size=(1,5))
b = np.random.randint(1,11, size=(1,5))
sum = a+b
subs = a-b
mult = a*b
print(sum)
print(subs)
print(mult)

[[10 10 10 10  3]]
[[ 4 10  5 10  8]]
[[14 20 15 20 11]]
[[ 6  0  5  0 -5]]
[[ 40 100  50 100  24]]


In [33]:
a = np.random.randn(7)
b = np.random.randn(7)
scalar = np.dot(a, b)
print(scalar)

[ 0.25214177 -0.4015616  -0.01877124  0.0245224   1.58132501  0.93710022
 -0.31194567]
[ 0.08072646 -0.67175028  0.03983537 -0.52615392 -0.6650955  -1.69085372
  0.37285714]
-2.4760893916685474


In [37]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,3))
ab = np.dot(a,b)
print(ab)

[[7 3]
 [3 8]]
[[ 2 10  9]
 [ 2  1  5]]
[[20 73 78]
 [22 38 67]]


In [39]:
a = np.random.randint(1,11, size=(3,3))
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 6  3  7]
 [ 7  4  9]
 [ 9  3 10]]
[[ 2.16666667 -1.5        -0.16666667]
 [ 1.83333333 -0.5        -0.83333333]
 [-2.5         1.5         0.5       ]]


In [40]:
a = np.random.random((4,4))
a_t = a.T
print(a_t)

[[0.8838159  0.64841649 0.4268674  0.36322926]
 [0.27319106 0.76282762 0.17239819 0.3263816 ]
 [0.38407418 0.20096243 0.40290641 0.47111515]
 [0.26210415 0.79409374 0.7826932  0.94874145]]
[[0.8838159  0.27319106 0.38407418 0.26210415]
 [0.64841649 0.76282762 0.20096243 0.79409374]
 [0.4268674  0.17239819 0.40290641 0.7826932 ]
 [0.36322926 0.3263816  0.47111515 0.94874145]]


In [42]:
a = np.random.randint(1,11, size=(3,4))
b = np.random.randint(1,11, size=(4))
ab = np.dot(a,b)
print(ab)

[[ 3  7 10  4]
 [10  2  8  6]
 [ 5  4 10 10]]
[7 5 1 2]
[ 74 100  85]


In [46]:
a = np.random.random((2,3))
b = np.random.random((3))
ab = np.dot(a,b)
print(ab)

[[0.60062951 0.19772406 0.50636128]
 [0.4360854  0.71700591 0.03784971]]
[0.70738356 0.78218306 0.05877534]
[0.60929341 0.87153415]


In [53]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
ab = a*b
print(ab)

[[60  7]
 [80  8]]


In [48]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
ab = np.dot(a,b)
print(ab)

[[103 108]
 [ 53  23]]


In [52]:
a = np.random.randint(1,101, size=(5,5))
sum = a.sum()
print(sum)

1161


In [54]:
a = np.random.randint(1,11, size=(4,4))
b = np.random.randint(1,11, size=(4,4))
subs = a - b
print(subs)

[[2 9 8 1]
 [4 2 1 3]
 [9 3 6 7]
 [5 5 3 9]]
[[ 5  9  8  3]
 [ 3  1  5  4]
 [ 4  4  7  5]
 [ 2 10  9  3]]
[[-3  0  0 -2]
 [ 1  1 -4 -1]
 [ 5 -1 -1  2]
 [ 3 -5 -6  6]]


In [58]:
a = np.random.random((3,3))
row_sum = np.sum(a, axis=1).reshape(-1, 1)
print(a)
print(row_sum)

[[0.91117408 0.81537297 0.11589014]
 [0.58475531 0.29648242 0.78383145]
 [0.63597711 0.10660537 0.5181747 ]]
[[1.8424372 ]
 [1.66506918]
 [1.26075719]]


In [63]:
a = np.random.randint(1, 10, size=(3,4))
a_square = np.square(a)
print(a)
print(a_square)

[[2 4 7 4]
 [2 2 8 4]
 [5 4 3 1]]
[[ 4 16 49 16]
 [ 4  4 64 16]
 [25 16  9  1]]


In [64]:
a = np.random.randint(1,51, size=(4))
a_sqrt = np.sqrt(a)
print(a)
print(a_sqrt)

[24 11 23 32]
[4.89897949 3.31662479 4.79583152 5.65685425]
